# Generated by Django 6.0.7 on 2026-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together={('product', 'name')},
        ),
        migrations.AddConstraint(
            model_name='subvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_guard_positive'),
        ),
    ]
