# Generated by Django 6.0.7 on 2026-07-09 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_subvariant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['ProductCode'], name='products_pr_Product_c1dc86_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['ProductName'], name='products_pr_Product_c58fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['Category'], name='products_pr_Categor_0cb6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='inventory_p_product_cc68de_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['sub_variant'], name='inventory_s_sub_var_7f9400_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_s_transac_f888de_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='inventory_s_created_ff5dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='subvariant',
            index=models.Index(fields=['product'], name='inventory_s_product_abbc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['variant'], name='inventory_v_variant_8adab6_idx'),
        ),
    ]
